FROM node:alpine

RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/frontend

WORKDIR /usr/src/app/frontend

COPY package*.json ./
RUN npm install

ENV DEV_BACKEND_URL="http://localhost:8080"

COPY . .

EXPOSE 5800

CMD ["npm","run","dev"]
